language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - pip install -r dev-requirements.txt
    - pip install -e .
# command to run tests
script: py.test --cov=neoalchemy
after_success: codecov
