language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r dev_requirements.txt"
# command to run tests
script: coverage run --source=neoalchemy setup.py test
after_success: codecov
